import type { SubjectRecord } from '@/types/subject';

export const SUBJECTS: SubjectRecord[] = [
  // ACTIVE
  {
    id: 'subj-ariadne',
    codename: 'ARIADNE',
    status: 'DECEASED',
    summary: `Subject reported deceased 2019-04-11. Manner of death: uncontested at time of filing. Three subsequent sightings have been logged and not explained. The file remains formally closed.`,
    firstObserved: '2016-09-03T00:00:00Z',
    relatedDossiers: ['n13-001-ariadne'],
    aliases: ['THREAD', 'LOOM-7'],
  },
  {
    id: 'subj-cygnus',
    codename: 'CYGNUS',
    status: 'ACTIVE',
    summary: `Field operator. Last confirmed position: Helsinki, 2024-11-02. No evidence of compromise. Involvement in the ARIADNE case remains unconfirmed at the file level.`,
    firstObserved: '2018-03-17T00:00:00Z',
    relatedDossiers: ['n13-001-ariadne'],
  },
  {
    id: 'subj-vesper',
    codename: 'VESPER',
    status: 'UNKNOWN',
    summary: `Source of transmissions on band 17.3 MHz — a frequency that does not appear on any registered spectrum allocation. Identity unknown. May be a person, an automated system, or neither.`,
    firstObserved: '2021-03-08T00:00:00Z',
    relatedDossiers: ['n13-002-vesper'],
  },
  {
    id: 'subj-relay-delta',
    codename: 'RELAY-DELTA',
    status: 'UNKNOWN',
    summary: `Suspected relay node for VESPER transmissions. Geolocated to an approximate 200 km radius in the northern Baltic. No physical identification has been possible.`,
    firstObserved: '2021-06-14T00:00:00Z',
    relatedDossiers: ['n13-002-vesper'],
  },
  {
    id: 'subj-kairos',
    codename: 'KAIROS',
    status: 'REDACTED',
    summary: `[CONTENT REDACTED // 13.4-CTRL]`,
    firstObserved: '2018-11-01T00:00:00Z',
    relatedDossiers: ['n13-003-kairos'],
    aliases: ['[REDACTED]'],
  },
  {
    id: 'subj-loom',
    codename: 'LOOM',
    status: 'ACTIVE',
    summary: `Administrative handler for several subjects in this registry. Filed the ARIADNE closure report in 2019. Continues to log queries against closed cases without stated reason.`,
    firstObserved: '2015-04-22T00:00:00Z',
    relatedDossiers: ['n13-001-ariadne', 'n13-004-meridian'],
  },
  {
    id: 'subj-meridian',
    codename: 'MERIDIAN',
    status: 'UNKNOWN',
    summary: `Subject of a six-year investigation closed without public resolution. The closure documentation runs to four pages. Investigations of this scope typically produce several hundred. The brevity is the anomaly.`,
    firstObserved: '2017-06-14T00:00:00Z',
    relatedDossiers: ['n13-004-meridian'],
  },
  {
    id: 'subj-anchor',
    codename: 'ANCHOR',
    status: 'DECEASED',
    summary: `Witness in the MERIDIAN investigation. Died 2022-09-17 before a formal deposition was recorded. Cause of death listed as uncontested. The deposition has not been reconstructed from notes.`,
    firstObserved: '2019-02-08T00:00:00Z',
    relatedDossiers: ['n13-004-meridian'],
  },
  {
    id: 'subj-watcher',
    codename: 'WATCHER',
    status: 'REDACTED',
    summary: `[CONTENT REDACTED // 13.4-CTRL]`,
    firstObserved: '2020-07-30T00:00:00Z',
    relatedDossiers: ['n13-003-kairos', 'n13-004-meridian'],
  },
];
